development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: myBlog
  username: 'Blog'
  password: 'BlogApp'

test:
  <<: *default
  database: firstApp_test

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: myBlog
  username: 'Blog'
  password: 'BlogApp'
